/* Generated by re2c 3.1 on Wed Apr  1 00:31:55 2026 */
// SPDX-License-Identifier: MIT
// Copyright (c) 2026-present Tian Liao

// std
#include <cassert>
#include <cctype>

// epx
#include "lexer.hpp"

namespace epx::script {

std::expected<token, token_ec> lexer::operator()() noexcept {
  const char* end = input_.data() + input_.length();
  auto getch = [&]() noexcept -> std::expected<char, token_ec> {
    while (cursor_ < end && std::isspace(static_cast<unsigned char>(*cursor_))) {
      ++cursor_;
    }
    if (cursor_ == end) {
      return std::unexpected{token_ec::eof};
    }
    return *cursor_;
  };
  return getch().transform([&](char ch) noexcept -> token {
    auto try_lex_z = [&](const char* cursor) noexcept -> std::expected<token_integer_literal, int> {
      assert(cursor < end);
      if (*cursor == 'z') {
        if (cursor + 2 < end && *(cursor + 1) == '\'') {
          cursor += 2;
        } else {
          return std::unexpected{1};
        }
      }
      size_t len = 0;
      while (cursor < end && std::isdigit(static_cast<unsigned char>(*cursor))) {
        ++len;
      }
      if (len == 0) {
        return std::unexpected{2};
      } else {
        cursor_ = cursor;
        return token_integer_literal{.raw = std::string_view{cursor, len}};
      }
    };
    auto try_lex_r = [&]() noexcept -> std::expected<token_realnumber_literal, int> { abort(); };
    switch (ch) {
      case '*':
        ++cursor_;
        return token_op_mul{};
      case '/':
        ++cursor_;
        return token_op_div{};
      case '(':
        ++cursor_;
        return token_lparen{};
      case ')':
        ++cursor_;
        return token_rparen{};
      case '%':
        ++cursor_;
        return token_op_percent{};
      case '+': {
        const char* next = cursor_ + 1;
        if (next == end) {
          ++cursor_;
          return token_op_plus{};
        } else if (std::isdigit(static_cast<unsigned char>(*next)) || *next == 'r') {
          return try_lex_r()
              .transform_error([&](int) {
                ++cursor_;
                return token_op_plus{};
              })
              .value();
        } else if (*next == 'z') {
          return try_lex_z(next)
              .transform_error([&](int) {
                ++cursor_;
                return token_op_plus{};
              })
              .value();
        }
        ++cursor_;
        return token_op_plus{};
      }
      case '-': {
        const char* next = cursor_ + 1;
        if (next == end) {
          ++cursor_;
          return token_op_minus{};
        } else if (std::isdigit(static_cast<unsigned char>(*next)) || *next == 'r') {
          return try_lex_r()
              .transform([](token_realnumber_literal literal) {
                literal.negative = true;
                return literal;
              })
              .transform_error([&](int) {
                ++cursor_;
                return token_op_minus{};
              })
              .value();
        } else if (*next == 'z') {
          return try_lex_z(next)
              .transform([](token_integer_literal literal) {
                literal.negative = true;
                return literal;
              })
              .transform_error([&](int) {
                ++cursor_;
                return token_op_minus{};
              })
              .value();
        }
        ++cursor_;
        return token_op_minus{};
      }
    }
    abort();
  });
}

}  // namespace epx::script
